PBD-5263 Don't exclude xstream
because xstream is involved in the Java exceptions (in build-jobs repo)
for keepLongStdio not being found:

com.thoughtworks.xstream.mapper.CannotResolveClassException: keepLongStdio